### PR TITLE
Automated Compiler Flags Optimization for Multiple ARM Architectures

### PR DESCRIPTION
**Pull request by simeononsecurity**
This pull request introduces an automated script that optimizes compiler flags based on the detected CPU architecture. The script covers a range of ARM architectures, including armv8-a, armv7-a, armv7ve, armv6zk, and armv6, allowing for more efficient compilation tailored to different hardware configurations.

**Key Features:**
- Automatically detects the CPU architecture using system tools.
- Sets architecture-specific flags for various ARM architectures, enhancing code performance.
- Includes common compiler optimization flags and vectorization options.
- Provides a flexible and extensible structure to accommodate additional architectures.

**Usage Instructions:**
1. Clone this repository.
2. Run the script on your target system.
3. The script will detect the architecture and apply the appropriate compiler flags.
4. The configured build will incorporate the optimized flags for enhanced performance.

This enhancement contributes to better performance and efficiency when compiling projects on ARM-based systems. Please review and provide feedback. Thank you for considering this pull request!

I should note, however, I was only able to test this on the two most modern architectures.

### CODE REVIEW

**Comment by Oink70** [comment]
I will create a dev-branch for that and test the functionality, before merging into the main chain.

**Comment by simeononsecurity** [comment]
Yeah further looking into this, this will require switching to GCC as the compiler and not using clang. 
Clang doesn't offer configurations for these optimizations.
Not sure what all changes that will require. I'm looking into it still.

**Review by Darktron — COMMENTED** [review]
No cortex a77?

**Comment by Darktron** [comment]
> I will create a dev-branch for that and test the functionality, before merging into the main chain.

I can test builds for you. I have SD855, SD855+, SD865, SD8Gen1, SD8Gen2.

**Comment by simeononsecurity** [comment]
> No cortex a77?

Seems in clang v16 and v18 there are no valid specifically a77 optimizations. Even though they are documented in the clang documentation, the option isn't enabled. 
You can see what I'm working on here. Practically done, we're just working on getting the CI/CD working for automatic releases when updating. Supported builds are "Cortex-A53" "Cortex-A55" "Cortex-A57" "Cortex-A72" "Cortex-A73" "Cortex-A75" "Cortex-A76" "Cortex-A78c" "Cortex-A78". 
https://github.com/simeononsecurity/CCminer-ARM-optimized

If you don't have one of those cores, and want to assemble one of the builds, just run the github-action.sh script in the path and it'll build all versions.

**Pull request closed without merging**
